/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnboardingWithTenant } from '../../models/onboarding-with-tenant';

export interface GetOnboardingApiV1OnboardingIdGet$Params {
  id: number;
}

export function getOnboardingApiV1OnboardingIdGet(http: HttpClient, rootUrl: string, params: GetOnboardingApiV1OnboardingIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OnboardingWithTenant>> {
  const rb = new RequestBuilder(rootUrl, getOnboardingApiV1OnboardingIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnboardingWithTenant>;
    })
  );
}

getOnboardingApiV1OnboardingIdGet.PATH = '/api/v1/onboarding/{id}';
