/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnboardingStatus } from '../../models/onboarding-status';
import { OnboardingWithTenant } from '../../models/onboarding-with-tenant';

export interface ListOnboardingApiV1OnboardingGet$Params {
  status?: (OnboardingStatus | null);
  skip?: number;
  limit?: number;
}

export function listOnboardingApiV1OnboardingGet(http: HttpClient, rootUrl: string, params?: ListOnboardingApiV1OnboardingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OnboardingWithTenant>>> {
  const rb = new RequestBuilder(rootUrl, listOnboardingApiV1OnboardingGet.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OnboardingWithTenant>>;
    })
  );
}

listOnboardingApiV1OnboardingGet.PATH = '/api/v1/onboarding/';
