/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnboardingRead } from '../../models/onboarding-read';
import { OnboardingUpdate } from '../../models/onboarding-update';

export interface UpdateOnboardingApiV1OnboardingIdPatch$Params {
  id: number;
      body: OnboardingUpdate
}

export function updateOnboardingApiV1OnboardingIdPatch(http: HttpClient, rootUrl: string, params: UpdateOnboardingApiV1OnboardingIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<OnboardingRead>> {
  const rb = new RequestBuilder(rootUrl, updateOnboardingApiV1OnboardingIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnboardingRead>;
    })
  );
}

updateOnboardingApiV1OnboardingIdPatch.PATH = '/api/v1/onboarding/{id}';
