/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PerformanceMetrics } from '../../models/performance-metrics';

export interface GetPerformanceMetricsApiV1FleeterPerformanceGet$Params {
}

export function getPerformanceMetricsApiV1FleeterPerformanceGet(http: HttpClient, rootUrl: string, params?: GetPerformanceMetricsApiV1FleeterPerformanceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PerformanceMetrics>> {
  const rb = new RequestBuilder(rootUrl, getPerformanceMetricsApiV1FleeterPerformanceGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PerformanceMetrics>;
    })
  );
}

getPerformanceMetricsApiV1FleeterPerformanceGet.PATH = '/api/v1/fleeter/performance/';
