/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyApproveBrandingApiV1TenantsMeBrandingApprovePost } from '../../models/body-approve-branding-api-v-1-tenants-me-branding-approve-post';
import { TenantRead } from '../../models/tenant-read';

export interface ApproveBrandingApiV1TenantsMeBrandingApprovePost$Params {
      body: BodyApproveBrandingApiV1TenantsMeBrandingApprovePost
}

export function approveBrandingApiV1TenantsMeBrandingApprovePost(http: HttpClient, rootUrl: string, params: ApproveBrandingApiV1TenantsMeBrandingApprovePost$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantRead>> {
  const rb = new RequestBuilder(rootUrl, approveBrandingApiV1TenantsMeBrandingApprovePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantRead>;
    })
  );
}

approveBrandingApiV1TenantsMeBrandingApprovePost.PATH = '/api/v1/tenants/me/branding-approve';
