/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionPlanRead } from '../../models/subscription-plan-read';

export interface ListPlansApiV1TenantsPlansGet$Params {
}

export function listPlansApiV1TenantsPlansGet(http: HttpClient, rootUrl: string, params?: ListPlansApiV1TenantsPlansGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubscriptionPlanRead>>> {
  const rb = new RequestBuilder(rootUrl, listPlansApiV1TenantsPlansGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubscriptionPlanRead>>;
    })
  );
}

listPlansApiV1TenantsPlansGet.PATH = '/api/v1/tenants/plans';
