/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantRead } from '../../models/tenant-read';

export interface ReadCurrentTenantApiV1TenantsMeGet$Params {
}

export function readCurrentTenantApiV1TenantsMeGet(http: HttpClient, rootUrl: string, params?: ReadCurrentTenantApiV1TenantsMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantRead>> {
  const rb = new RequestBuilder(rootUrl, readCurrentTenantApiV1TenantsMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantRead>;
    })
  );
}

readCurrentTenantApiV1TenantsMeGet.PATH = '/api/v1/tenants/me';
