/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantRead } from '../../models/tenant-read';
import { TenantUpdate } from '../../models/tenant-update';

export interface UpdateCurrentTenantApiV1TenantsMePatch$Params {
      body: TenantUpdate
}

export function updateCurrentTenantApiV1TenantsMePatch(http: HttpClient, rootUrl: string, params: UpdateCurrentTenantApiV1TenantsMePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantRead>> {
  const rb = new RequestBuilder(rootUrl, updateCurrentTenantApiV1TenantsMePatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantRead>;
    })
  );
}

updateCurrentTenantApiV1TenantsMePatch.PATH = '/api/v1/tenants/me';
