/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantRead } from '../../models/tenant-read';
import { UpgradeRequest } from '../../models/upgrade-request';

export interface UpgradePlanApiV1TenantsUpgradePost$Params {
      body: UpgradeRequest
}

export function upgradePlanApiV1TenantsUpgradePost(http: HttpClient, rootUrl: string, params: UpgradePlanApiV1TenantsUpgradePost$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantRead>> {
  const rb = new RequestBuilder(rootUrl, upgradePlanApiV1TenantsUpgradePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantRead>;
    })
  );
}

upgradePlanApiV1TenantsUpgradePost.PATH = '/api/v1/tenants/upgrade';
