/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskCreate } from '../../models/task-create';
import { TaskRead } from '../../models/task-read';

export interface CreateTaskApiV1TasksPost$Params {
      body: TaskCreate
}

export function createTaskApiV1TasksPost(http: HttpClient, rootUrl: string, params: CreateTaskApiV1TasksPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskRead>> {
  const rb = new RequestBuilder(rootUrl, createTaskApiV1TasksPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskRead>;
    })
  );
}

createTaskApiV1TasksPost.PATH = '/api/v1/tasks/';
