/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskStatus } from '../../models/task-status';
import { TaskWithContext } from '../../models/task-with-context';

export interface ListTasksApiV1TasksGet$Params {
  status?: (TaskStatus | null);
  skip?: number;
  limit?: number;
}

export function listTasksApiV1TasksGet(http: HttpClient, rootUrl: string, params?: ListTasksApiV1TasksGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskWithContext>>> {
  const rb = new RequestBuilder(rootUrl, listTasksApiV1TasksGet.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskWithContext>>;
    })
  );
}

listTasksApiV1TasksGet.PATH = '/api/v1/tasks/';
