/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskRead } from '../../models/task-read';
import { TaskUpdate } from '../../models/task-update';

export interface UpdateTaskApiV1TasksIdPatch$Params {
  id: number;
      body: TaskUpdate
}

export function updateTaskApiV1TasksIdPatch(http: HttpClient, rootUrl: string, params: UpdateTaskApiV1TasksIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskRead>> {
  const rb = new RequestBuilder(rootUrl, updateTaskApiV1TasksIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskRead>;
    })
  );
}

updateTaskApiV1TasksIdPatch.PATH = '/api/v1/tasks/{id}';
