/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetQrImageApiV1LocationsIdQrImageGet$Params {
  id: number;
  form_slug: string;
}

export function getQrImageApiV1LocationsIdQrImageGet(http: HttpClient, rootUrl: string, params: GetQrImageApiV1LocationsIdQrImageGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getQrImageApiV1LocationsIdQrImageGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('form_slug', params.form_slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getQrImageApiV1LocationsIdQrImageGet.PATH = '/api/v1/locations/{id}/qr_image';
