/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocationRead } from '../../models/location-read';

export interface ReadLocationsApiV1LocationsGet$Params {
  skip?: number;
  limit?: number;
}

export function readLocationsApiV1LocationsGet(http: HttpClient, rootUrl: string, params?: ReadLocationsApiV1LocationsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationRead>>> {
  const rb = new RequestBuilder(rootUrl, readLocationsApiV1LocationsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LocationRead>>;
    })
  );
}

readLocationsApiV1LocationsGet.PATH = '/api/v1/locations/';
