/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocationRead } from '../../models/location-read';
import { LocationUpdate } from '../../models/location-update';

export interface UpdateLocationApiV1LocationsIdPut$Params {
  id: number;
      body: LocationUpdate
}

export function updateLocationApiV1LocationsIdPut(http: HttpClient, rootUrl: string, params: UpdateLocationApiV1LocationsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<LocationRead>> {
  const rb = new RequestBuilder(rootUrl, updateLocationApiV1LocationsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LocationRead>;
    })
  );
}

updateLocationApiV1LocationsIdPut.PATH = '/api/v1/locations/{id}';
