"""Add branding fields and LetterheadAsset

Revision ID: 374dbcbfd794
Revises: c6d721894a90
Create Date: 2026-01-03 15:54:26.483838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '374dbcbfd794'
down_revision: Union[str, Sequence[str], None] = 'c6d721894a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_position', sqlmodel.sql.sqltypes.AutoString(), server_default='top-left', nullable=False))
        batch_op.add_column(sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('is_branding_approved', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('brand_color')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_color', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_branding_approved')
        batch_op.drop_column('address')
        batch_op.drop_column('font_family')
        batch_op.drop_column('accent_color')
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('logo_position')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
