"""Add AI fields to Values

Revision ID: c6d721894a90
Revises: 
Create Date: 2026-01-01 12:14:05.596347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6d721894a90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('values', sa.Column('ai_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('values', 'ai_analysis')
    op.drop_column('values', 'sentiment')
    # ### end Alembic commands ###
