/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserRead } from '../../models/user-read';

export interface ReadUserMeApiV1UsersMeGet$Params {
}

export function readUserMeApiV1UsersMeGet(http: HttpClient, rootUrl: string, params?: ReadUserMeApiV1UsersMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRead>> {
  const rb = new RequestBuilder(rootUrl, readUserMeApiV1UsersMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserRead>;
    })
  );
}

readUserMeApiV1UsersMeGet.PATH = '/api/v1/users/me';
