/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserRead } from '../../models/user-read';
import { UserUpdate } from '../../models/user-update';

export interface UpdateUserMeApiV1UsersMePatch$Params {
      body: UserUpdate
}

export function updateUserMeApiV1UsersMePatch(http: HttpClient, rootUrl: string, params: UpdateUserMeApiV1UsersMePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRead>> {
  const rb = new RequestBuilder(rootUrl, updateUserMeApiV1UsersMePatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserRead>;
    })
  );
}

updateUserMeApiV1UsersMePatch.PATH = '/api/v1/users/me';
