/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyLoginEndpointApiV1AuthLoginPost } from '../../models/body-login-endpoint-api-v-1-auth-login-post';

export interface LoginEndpointApiV1AuthLoginPost$Params {
      body: BodyLoginEndpointApiV1AuthLoginPost
}

export function loginEndpointApiV1AuthLoginPost(http: HttpClient, rootUrl: string, params: LoginEndpointApiV1AuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, loginEndpointApiV1AuthLoginPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

loginEndpointApiV1AuthLoginPost.PATH = '/api/v1/auth/login';
