/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyLoginAccessTokenApiV1LoginAccessTokenPost } from '../../models/body-login-access-token-api-v-1-login-access-token-post';

export interface LoginAccessTokenApiV1LoginAccessTokenPost$Params {
      body: BodyLoginAccessTokenApiV1LoginAccessTokenPost
}

export function loginAccessTokenApiV1LoginAccessTokenPost(http: HttpClient, rootUrl: string, params: LoginAccessTokenApiV1LoginAccessTokenPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, loginAccessTokenApiV1LoginAccessTokenPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

loginAccessTokenApiV1LoginAccessTokenPost.PATH = '/api/v1/login/access-token';
