/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormCreate } from '../../models/form-create';
import { FormRead } from '../../models/form-read';

export interface CreateFormApiV1FormsPost$Params {
      body: FormCreate
}

export function createFormApiV1FormsPost(http: HttpClient, rootUrl: string, params: CreateFormApiV1FormsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FormRead>> {
  const rb = new RequestBuilder(rootUrl, createFormApiV1FormsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormRead>;
    })
  );
}

createFormApiV1FormsPost.PATH = '/api/v1/forms/';
