/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ExportFeedbackCsvApiV1FormsIdExportGet$Params {
  id: number;
  location_id?: (number | null);
  start_date?: (string | null);
  end_date?: (string | null);
}

export function exportFeedbackCsvApiV1FormsIdExportGet(http: HttpClient, rootUrl: string, params: ExportFeedbackCsvApiV1FormsIdExportGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, exportFeedbackCsvApiV1FormsIdExportGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('location_id', params.location_id, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

exportFeedbackCsvApiV1FormsIdExportGet.PATH = '/api/v1/forms/{id}/export';
