/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicFormRead } from '../../models/public-form-read';

export interface GetPublicFormApiV1FormsPublicSlugGet$Params {
  slug: string;
}

export function getPublicFormApiV1FormsPublicSlugGet(http: HttpClient, rootUrl: string, params: GetPublicFormApiV1FormsPublicSlugGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicFormRead>> {
  const rb = new RequestBuilder(rootUrl, getPublicFormApiV1FormsPublicSlugGet.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicFormRead>;
    })
  );
}

getPublicFormApiV1FormsPublicSlugGet.PATH = '/api/v1/forms/public/{slug}';
