/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeedbackStat } from '../../models/feedback-stat';

export interface GetFormStatsApiV1FormsIdStatsGet$Params {
  id: number;
  location_id?: (number | null);
  start_date?: (string | null);
  end_date?: (string | null);
}

export function getFormStatsApiV1FormsIdStatsGet(http: HttpClient, rootUrl: string, params: GetFormStatsApiV1FormsIdStatsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FeedbackStat>> {
  const rb = new RequestBuilder(rootUrl, getFormStatsApiV1FormsIdStatsGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('location_id', params.location_id, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeedbackStat>;
    })
  );
}

getFormStatsApiV1FormsIdStatsGet.PATH = '/api/v1/forms/{id}/stats';
