/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormRead } from '../../models/form-read';

export interface ReadFormsApiV1FormsGet$Params {
  skip?: number;
  limit?: number;
}

export function readFormsApiV1FormsGet(http: HttpClient, rootUrl: string, params?: ReadFormsApiV1FormsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FormRead>>> {
  const rb = new RequestBuilder(rootUrl, readFormsApiV1FormsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FormRead>>;
    })
  );
}

readFormsApiV1FormsGet.PATH = '/api/v1/forms/';
