/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormRead } from '../../models/form-read';

export interface SetDefaultFormApiV1FormsIdSetDefaultPost$Params {
  id: number;
}

export function setDefaultFormApiV1FormsIdSetDefaultPost(http: HttpClient, rootUrl: string, params: SetDefaultFormApiV1FormsIdSetDefaultPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FormRead>> {
  const rb = new RequestBuilder(rootUrl, setDefaultFormApiV1FormsIdSetDefaultPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormRead>;
    })
  );
}

setDefaultFormApiV1FormsIdSetDefaultPost.PATH = '/api/v1/forms/{id}/set_default';
