/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValuesCreate } from '../../models/values-create';

export interface SubmitFeedbackApiV1FormsPublicFeedbackPost$Params {
      body: ValuesCreate
}

export function submitFeedbackApiV1FormsPublicFeedbackPost(http: HttpClient, rootUrl: string, params: SubmitFeedbackApiV1FormsPublicFeedbackPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, submitFeedbackApiV1FormsPublicFeedbackPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

submitFeedbackApiV1FormsPublicFeedbackPost.PATH = '/api/v1/forms/public/feedback';
