/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormRead } from '../../models/form-read';
import { FormUpdate } from '../../models/form-update';

export interface UpdateFormApiV1FormsIdPut$Params {
  id: number;
      body: FormUpdate
}

export function updateFormApiV1FormsIdPut(http: HttpClient, rootUrl: string, params: UpdateFormApiV1FormsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<FormRead>> {
  const rb = new RequestBuilder(rootUrl, updateFormApiV1FormsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormRead>;
    })
  );
}

updateFormApiV1FormsIdPut.PATH = '/api/v1/forms/{id}';
