/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EscalateToSupportApiV1FleeterTenantsTenantIdEscalatePost$Params {
  tenant_id: number;
  reason: string;
}

export function escalateToSupportApiV1FleeterTenantsTenantIdEscalatePost(http: HttpClient, rootUrl: string, params: EscalateToSupportApiV1FleeterTenantsTenantIdEscalatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, escalateToSupportApiV1FleeterTenantsTenantIdEscalatePost.PATH, 'post');
  if (params) {
    rb.path('tenant_id', params.tenant_id, {});
    rb.query('reason', params.reason, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

escalateToSupportApiV1FleeterTenantsTenantIdEscalatePost.PATH = '/api/v1/fleeter/tenants/{tenant_id}/escalate';
