/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantSalesView } from '../../models/tenant-sales-view';

export interface ListAssignedTenantsApiV1FleeterTenantsGet$Params {
}

export function listAssignedTenantsApiV1FleeterTenantsGet(http: HttpClient, rootUrl: string, params?: ListAssignedTenantsApiV1FleeterTenantsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TenantSalesView>>> {
  const rb = new RequestBuilder(rootUrl, listAssignedTenantsApiV1FleeterTenantsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TenantSalesView>>;
    })
  );
}

listAssignedTenantsApiV1FleeterTenantsGet.PATH = '/api/v1/fleeter/tenants/';
