/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ConvertLeadToTenantApiV1LeadsIdConvertPost$Params {
  id: number;
}

export function convertLeadToTenantApiV1LeadsIdConvertPost(http: HttpClient, rootUrl: string, params: ConvertLeadToTenantApiV1LeadsIdConvertPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: any;
}>> {
  const rb = new RequestBuilder(rootUrl, convertLeadToTenantApiV1LeadsIdConvertPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: any;
      }>;
    })
  );
}

convertLeadToTenantApiV1LeadsIdConvertPost.PATH = '/api/v1/leads/{id}/convert';
