/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FollowUpCreate } from '../../models/follow-up-create';
import { FollowUpRead } from '../../models/follow-up-read';

export interface CreateFollowUpApiV1LeadsIdFollowUpsPost$Params {
  id: number;
      body: FollowUpCreate
}

export function createFollowUpApiV1LeadsIdFollowUpsPost(http: HttpClient, rootUrl: string, params: CreateFollowUpApiV1LeadsIdFollowUpsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FollowUpRead>> {
  const rb = new RequestBuilder(rootUrl, createFollowUpApiV1LeadsIdFollowUpsPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FollowUpRead>;
    })
  );
}

createFollowUpApiV1LeadsIdFollowUpsPost.PATH = '/api/v1/leads/{id}/follow-ups';
