/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeadCreate } from '../../models/lead-create';
import { LeadRead } from '../../models/lead-read';

export interface CreateLeadApiV1LeadsPost$Params {
      body: LeadCreate
}

export function createLeadApiV1LeadsPost(http: HttpClient, rootUrl: string, params: CreateLeadApiV1LeadsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<LeadRead>> {
  const rb = new RequestBuilder(rootUrl, createLeadApiV1LeadsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeadRead>;
    })
  );
}

createLeadApiV1LeadsPost.PATH = '/api/v1/leads/';
