/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeadWithFollowUps } from '../../models/lead-with-follow-ups';

export interface GetLeadApiV1LeadsIdGet$Params {
  id: number;
}

export function getLeadApiV1LeadsIdGet(http: HttpClient, rootUrl: string, params: GetLeadApiV1LeadsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<LeadWithFollowUps>> {
  const rb = new RequestBuilder(rootUrl, getLeadApiV1LeadsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeadWithFollowUps>;
    })
  );
}

getLeadApiV1LeadsIdGet.PATH = '/api/v1/leads/{id}';
