/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FollowUpRead } from '../../models/follow-up-read';

export interface ListAllFollowUpsApiV1LeadsFollowUpsAllGet$Params {
}

export function listAllFollowUpsApiV1LeadsFollowUpsAllGet(http: HttpClient, rootUrl: string, params?: ListAllFollowUpsApiV1LeadsFollowUpsAllGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FollowUpRead>>> {
  const rb = new RequestBuilder(rootUrl, listAllFollowUpsApiV1LeadsFollowUpsAllGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FollowUpRead>>;
    })
  );
}

listAllFollowUpsApiV1LeadsFollowUpsAllGet.PATH = '/api/v1/leads/follow-ups/all';
