/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeadRead } from '../../models/lead-read';
import { LeadStatus } from '../../models/lead-status';

export interface ListLeadsApiV1LeadsGet$Params {
  skip?: number;
  limit?: number;
  status?: (LeadStatus | null);
  search?: (string | null);
}

export function listLeadsApiV1LeadsGet(http: HttpClient, rootUrl: string, params?: ListLeadsApiV1LeadsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeadRead>>> {
  const rb = new RequestBuilder(rootUrl, listLeadsApiV1LeadsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
    rb.query('status', params.status, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeadRead>>;
    })
  );
}

listLeadsApiV1LeadsGet.PATH = '/api/v1/leads/';
