/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeadRead } from '../../models/lead-read';
import { LeadUpdate } from '../../models/lead-update';

export interface UpdateLeadApiV1LeadsIdPatch$Params {
  id: number;
      body: LeadUpdate
}

export function updateLeadApiV1LeadsIdPatch(http: HttpClient, rootUrl: string, params: UpdateLeadApiV1LeadsIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<LeadRead>> {
  const rb = new RequestBuilder(rootUrl, updateLeadApiV1LeadsIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeadRead>;
    })
  );
}

updateLeadApiV1LeadsIdPatch.PATH = '/api/v1/leads/{id}';
