/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionPlan } from '../../models/subscription-plan';
import { SubscriptionPlanCreate } from '../../models/subscription-plan-create';

export interface CreatePlanApiV1AdminPlansPost$Params {
      body: SubscriptionPlanCreate
}

export function createPlanApiV1AdminPlansPost(http: HttpClient, rootUrl: string, params: CreatePlanApiV1AdminPlansPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SubscriptionPlan>> {
  const rb = new RequestBuilder(rootUrl, createPlanApiV1AdminPlansPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubscriptionPlan>;
    })
  );
}

createPlanApiV1AdminPlansPost.PATH = '/api/v1/admin/plans';
