/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeatureFlag } from '../../models/feature-flag';
import { FeatureFlagCreate } from '../../models/feature-flag-create';

export interface CreateFeatureApiV1AdminFeaturesPost$Params {
      body: FeatureFlagCreate
}

export function createFeatureApiV1AdminFeaturesPost(http: HttpClient, rootUrl: string, params: CreateFeatureApiV1AdminFeaturesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FeatureFlag>> {
  const rb = new RequestBuilder(rootUrl, createFeatureApiV1AdminFeaturesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeatureFlag>;
    })
  );
}

createFeatureApiV1AdminFeaturesPost.PATH = '/api/v1/admin/features';
