/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tenant } from '../../models/tenant';
import { TenantCreateRequest } from '../../models/tenant-create-request';

export interface CreateTenantAdminApiV1AdminTenantsPost$Params {
      body: TenantCreateRequest
}

export function createTenantAdminApiV1AdminTenantsPost(http: HttpClient, rootUrl: string, params: CreateTenantAdminApiV1AdminTenantsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
  const rb = new RequestBuilder(rootUrl, createTenantAdminApiV1AdminTenantsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tenant>;
    })
  );
}

createTenantAdminApiV1AdminTenantsPost.PATH = '/api/v1/admin/tenants';
