/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteUserApiV1AdminUsersUserIdDelete$Params {
  user_id: number;
}

export function deleteUserApiV1AdminUsersUserIdDelete(http: HttpClient, rootUrl: string, params: DeleteUserApiV1AdminUsersUserIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, deleteUserApiV1AdminUsersUserIdDelete.PATH, 'delete');
  if (params) {
    rb.path('user_id', params.user_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

deleteUserApiV1AdminUsersUserIdDelete.PATH = '/api/v1/admin/users/{user_id}';
