/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SystemHealth } from '../../models/system-health';

export interface GetSystemHealthApiV1AdminMetricsHealthGet$Params {
}

export function getSystemHealthApiV1AdminMetricsHealthGet(http: HttpClient, rootUrl: string, params?: GetSystemHealthApiV1AdminMetricsHealthGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SystemHealth>> {
  const rb = new RequestBuilder(rootUrl, getSystemHealthApiV1AdminMetricsHealthGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SystemHealth>;
    })
  );
}

getSystemHealthApiV1AdminMetricsHealthGet.PATH = '/api/v1/admin/metrics/health';
