/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantWithAdmin } from '../../models/tenant-with-admin';

export interface GetTenantApiV1AdminTenantsTenantIdGet$Params {
  tenant_id: number;
}

export function getTenantApiV1AdminTenantsTenantIdGet(http: HttpClient, rootUrl: string, params: GetTenantApiV1AdminTenantsTenantIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantWithAdmin>> {
  const rb = new RequestBuilder(rootUrl, getTenantApiV1AdminTenantsTenantIdGet.PATH, 'get');
  if (params) {
    rb.path('tenant_id', params.tenant_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantWithAdmin>;
    })
  );
}

getTenantApiV1AdminTenantsTenantIdGet.PATH = '/api/v1/admin/tenants/{tenant_id}';
