/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SystemSetting } from '../../models/system-setting';

export interface ListSettingsApiV1AdminSettingsGet$Params {
}

export function listSettingsApiV1AdminSettingsGet(http: HttpClient, rootUrl: string, params?: ListSettingsApiV1AdminSettingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SystemSetting>>> {
  const rb = new RequestBuilder(rootUrl, listSettingsApiV1AdminSettingsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SystemSetting>>;
    })
  );
}

listSettingsApiV1AdminSettingsGet.PATH = '/api/v1/admin/settings';
