/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantWithAdmin } from '../../models/tenant-with-admin';

export interface ListTenantsApiV1AdminTenantsGet$Params {
  skip?: number;
  limit?: number;
  search?: (string | null);
}

export function listTenantsApiV1AdminTenantsGet(http: HttpClient, rootUrl: string, params?: ListTenantsApiV1AdminTenantsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TenantWithAdmin>>> {
  const rb = new RequestBuilder(rootUrl, listTenantsApiV1AdminTenantsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TenantWithAdmin>>;
    })
  );
}

listTenantsApiV1AdminTenantsGet.PATH = '/api/v1/admin/tenants';
