/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionPlan } from '../../models/subscription-plan';

export interface ListPlansApiV1AdminPlansGet$Params {
  skip?: number;
  limit?: number;
}

export function listPlansApiV1AdminPlansGet(http: HttpClient, rootUrl: string, params?: ListPlansApiV1AdminPlansGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubscriptionPlan>>> {
  const rb = new RequestBuilder(rootUrl, listPlansApiV1AdminPlansGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubscriptionPlan>>;
    })
  );
}

listPlansApiV1AdminPlansGet.PATH = '/api/v1/admin/plans';
