/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditLog } from '../../models/audit-log';

export interface ListAuditLogsApiV1AdminAuditLogsGet$Params {
  skip?: number;
  limit?: number;
  action?: (string | null);
  target_type?: (string | null);
  user_id?: (number | null);
}

export function listAuditLogsApiV1AdminAuditLogsGet(http: HttpClient, rootUrl: string, params?: ListAuditLogsApiV1AdminAuditLogsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AuditLog>>> {
  const rb = new RequestBuilder(rootUrl, listAuditLogsApiV1AdminAuditLogsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
    rb.query('action', params.action, {});
    rb.query('target_type', params.target_type, {});
    rb.query('user_id', params.user_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AuditLog>>;
    })
  );
}

listAuditLogsApiV1AdminAuditLogsGet.PATH = '/api/v1/admin/audit-logs';
