/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeatureFlag } from '../../models/feature-flag';

export interface ListFeaturesApiV1AdminFeaturesGet$Params {
  skip?: number;
  limit?: number;
}

export function listFeaturesApiV1AdminFeaturesGet(http: HttpClient, rootUrl: string, params?: ListFeaturesApiV1AdminFeaturesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FeatureFlag>>> {
  const rb = new RequestBuilder(rootUrl, listFeaturesApiV1AdminFeaturesGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FeatureFlag>>;
    })
  );
}

listFeaturesApiV1AdminFeaturesGet.PATH = '/api/v1/admin/features';
