/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';
import { UserRole } from '../../models/user-role';

export interface ListUsersApiV1AdminUsersGet$Params {
  skip?: number;
  limit?: number;
  role?: (UserRole | null);
  search?: (string | null);
}

export function listUsersApiV1AdminUsersGet(http: HttpClient, rootUrl: string, params?: ListUsersApiV1AdminUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<User>>> {
  const rb = new RequestBuilder(rootUrl, listUsersApiV1AdminUsersGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
    rb.query('role', params.role, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<User>>;
    })
  );
}

listUsersApiV1AdminUsersGet.PATH = '/api/v1/admin/users';
