/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordReset } from '../../models/password-reset';
import { User } from '../../models/user';

export interface ResetPasswordActionApiV1AdminUsersUserIdPasswordResetPost$Params {
  user_id: number;
      body: PasswordReset
}

export function resetPasswordActionApiV1AdminUsersUserIdPasswordResetPost(http: HttpClient, rootUrl: string, params: ResetPasswordActionApiV1AdminUsersUserIdPasswordResetPost$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
  const rb = new RequestBuilder(rootUrl, resetPasswordActionApiV1AdminUsersUserIdPasswordResetPost.PATH, 'post');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<User>;
    })
  );
}

resetPasswordActionApiV1AdminUsersUserIdPasswordResetPost.PATH = '/api/v1/admin/users/{user_id}/password_reset';
