/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionPlan } from '../../models/subscription-plan';

export interface SetDefaultPlanApiV1AdminPlansPlanIdDefaultPost$Params {
  plan_id: number;
}

export function setDefaultPlanApiV1AdminPlansPlanIdDefaultPost(http: HttpClient, rootUrl: string, params: SetDefaultPlanApiV1AdminPlansPlanIdDefaultPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SubscriptionPlan>> {
  const rb = new RequestBuilder(rootUrl, setDefaultPlanApiV1AdminPlansPlanIdDefaultPost.PATH, 'post');
  if (params) {
    rb.path('plan_id', params.plan_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubscriptionPlan>;
    })
  );
}

setDefaultPlanApiV1AdminPlansPlanIdDefaultPost.PATH = '/api/v1/admin/plans/{plan_id}/default';
