/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tenant } from '../../models/tenant';

export interface SuspendTenantApiV1AdminTenantsTenantIdSuspendPost$Params {
  tenant_id: number;
  suspend: boolean;
}

export function suspendTenantApiV1AdminTenantsTenantIdSuspendPost(http: HttpClient, rootUrl: string, params: SuspendTenantApiV1AdminTenantsTenantIdSuspendPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
  const rb = new RequestBuilder(rootUrl, suspendTenantApiV1AdminTenantsTenantIdSuspendPost.PATH, 'post');
  if (params) {
    rb.path('tenant_id', params.tenant_id, {});
    rb.query('suspend', params.suspend, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tenant>;
    })
  );
}

suspendTenantApiV1AdminTenantsTenantIdSuspendPost.PATH = '/api/v1/admin/tenants/{tenant_id}/suspend';
