/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeatureFlag } from '../../models/feature-flag';

export interface ToggleFeatureStatusApiV1AdminFeaturesFeatureIdTogglePost$Params {
  feature_id: number;
  is_enabled: boolean;
}

export function toggleFeatureStatusApiV1AdminFeaturesFeatureIdTogglePost(http: HttpClient, rootUrl: string, params: ToggleFeatureStatusApiV1AdminFeaturesFeatureIdTogglePost$Params, context?: HttpContext): Observable<StrictHttpResponse<FeatureFlag>> {
  const rb = new RequestBuilder(rootUrl, toggleFeatureStatusApiV1AdminFeaturesFeatureIdTogglePost.PATH, 'post');
  if (params) {
    rb.path('feature_id', params.feature_id, {});
    rb.query('is_enabled', params.is_enabled, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeatureFlag>;
    })
  );
}

toggleFeatureStatusApiV1AdminFeaturesFeatureIdTogglePost.PATH = '/api/v1/admin/features/{feature_id}/toggle';
