/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';

export interface ToggleUserStatusApiV1AdminUsersUserIdStatusPost$Params {
  user_id: number;
  is_active: boolean;
}

export function toggleUserStatusApiV1AdminUsersUserIdStatusPost(http: HttpClient, rootUrl: string, params: ToggleUserStatusApiV1AdminUsersUserIdStatusPost$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
  const rb = new RequestBuilder(rootUrl, toggleUserStatusApiV1AdminUsersUserIdStatusPost.PATH, 'post');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.query('is_active', params.is_active, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<User>;
    })
  );
}

toggleUserStatusApiV1AdminUsersUserIdStatusPost.PATH = '/api/v1/admin/users/{user_id}/status';
