/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionPlan } from '../../models/subscription-plan';
import { SubscriptionPlanCreate } from '../../models/subscription-plan-create';

export interface UpdatePlanApiV1AdminPlansPlanIdPut$Params {
  plan_id: number;
      body: SubscriptionPlanCreate
}

export function updatePlanApiV1AdminPlansPlanIdPut(http: HttpClient, rootUrl: string, params: UpdatePlanApiV1AdminPlansPlanIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<SubscriptionPlan>> {
  const rb = new RequestBuilder(rootUrl, updatePlanApiV1AdminPlansPlanIdPut.PATH, 'put');
  if (params) {
    rb.path('plan_id', params.plan_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubscriptionPlan>;
    })
  );
}

updatePlanApiV1AdminPlansPlanIdPut.PATH = '/api/v1/admin/plans/{plan_id}';
