/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeatureFlag } from '../../models/feature-flag';
import { FeatureFlagCreate } from '../../models/feature-flag-create';

export interface UpdateFeatureApiV1AdminFeaturesFeatureIdPut$Params {
  feature_id: number;
      body: FeatureFlagCreate
}

export function updateFeatureApiV1AdminFeaturesFeatureIdPut(http: HttpClient, rootUrl: string, params: UpdateFeatureApiV1AdminFeaturesFeatureIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<FeatureFlag>> {
  const rb = new RequestBuilder(rootUrl, updateFeatureApiV1AdminFeaturesFeatureIdPut.PATH, 'put');
  if (params) {
    rb.path('feature_id', params.feature_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeatureFlag>;
    })
  );
}

updateFeatureApiV1AdminFeaturesFeatureIdPut.PATH = '/api/v1/admin/features/{feature_id}';
