/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyUpdateTenantStatusApiV1AdminTenantsTenantIdStatusPatch } from '../../models/body-update-tenant-status-api-v-1-admin-tenants-tenant-id-status-patch';
import { Tenant } from '../../models/tenant';

export interface UpdateTenantStatusApiV1AdminTenantsTenantIdStatusPatch$Params {
  tenant_id: number;
      body: BodyUpdateTenantStatusApiV1AdminTenantsTenantIdStatusPatch
}

export function updateTenantStatusApiV1AdminTenantsTenantIdStatusPatch(http: HttpClient, rootUrl: string, params: UpdateTenantStatusApiV1AdminTenantsTenantIdStatusPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
  const rb = new RequestBuilder(rootUrl, updateTenantStatusApiV1AdminTenantsTenantIdStatusPatch.PATH, 'patch');
  if (params) {
    rb.path('tenant_id', params.tenant_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tenant>;
    })
  );
}

updateTenantStatusApiV1AdminTenantsTenantIdStatusPatch.PATH = '/api/v1/admin/tenants/{tenant_id}/status';
