/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SystemSetting } from '../../models/system-setting';
import { SystemSettingCreate } from '../../models/system-setting-create';

export interface UpdateSettingApiV1AdminSettingsKeyPut$Params {
  key: string;
      body: SystemSettingCreate
}

export function updateSettingApiV1AdminSettingsKeyPut(http: HttpClient, rootUrl: string, params: UpdateSettingApiV1AdminSettingsKeyPut$Params, context?: HttpContext): Observable<StrictHttpResponse<SystemSetting>> {
  const rb = new RequestBuilder(rootUrl, updateSettingApiV1AdminSettingsKeyPut.PATH, 'put');
  if (params) {
    rb.path('key', params.key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SystemSetting>;
    })
  );
}

updateSettingApiV1AdminSettingsKeyPut.PATH = '/api/v1/admin/settings/{key}';
