/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLog {
  action: string;
  created_at?: string;
  details?: {
[key: string]: any;
};
  id?: (number | null);
  target_id?: (string | null);
  target_type: string;
  user_email?: (string | null);
  user_id?: (number | null);
}
