/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyApproveBrandingApiV1TenantsMeBrandingApprovePost {
  accent_color?: (string | null);
  address?: (string | null);
  font_family?: string;
  logo_file?: (Blob | null);
  logo_position?: string;
  name: string;
  password: string;
  primary_color?: string;
  secondary_color?: (string | null);
  tagline?: (string | null);
}
