/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeatureFlag {
  created_at?: string;
  description?: (string | null);
  filters?: {
[key: string]: any;
};
  id?: (number | null);
  is_enabled?: boolean;
  name: string;
  rollout_percentage?: number;
}
