/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeatureFlagCreate {
  description?: (string | null);
  filters?: {
[key: string]: any;
};
  is_enabled?: boolean;
  name: string;
  rollout_percentage?: number;
}
