/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackStat {
  ai_summary?: (string | null);
  field_summaries?: {
[key: string]: any;
};
  recent_responses: Array<any>;
  total_responses: number;
}
