/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FollowUpStatus } from './follow-up-status';

/**
 * Each possible value of `FollowUpStatus`
 */
export const FOLLOW_UP_STATUS: FollowUpStatus[] = [
  'pending',
  'completed',
  'cancelled'
];