/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FollowUpStatus } from '../models/follow-up-status';
export interface FollowUpCreate {
  lead_id: number;
  notes?: (string | null);
  scheduled_at: string;
  status?: FollowUpStatus;
}
