/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormCreate {
  form_schema?: {
[key: string]: any;
};
  is_default?: boolean;
  is_published?: boolean;
  slug: string;
  title: string;
}
