/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormUpdate {
  form_schema?: ({
[key: string]: any;
} | null);
  is_default?: (boolean | null);
  is_published?: (boolean | null);
  slug?: (string | null);
  title?: (string | null);
}
