/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormRead {
  created_at: string;
  form_schema?: {
[key: string]: any;
};
  id: number;
  is_default?: boolean;
  is_published?: boolean;
  slug: string;
  tenant_id: number;
  title: string;
}
