/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeadStatus } from '../models/lead-status';
export interface LeadCreate {
  assigned_to_id?: (number | null);
  business_name: string;
  business_type?: (string | null);
  contact_person: string;
  email?: (string | null);
  notes?: (string | null);
  phone?: (string | null);
  status?: LeadStatus;
}
