/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FollowUpRead } from '../models/follow-up-read';
import { LeadStatus } from '../models/lead-status';
export interface LeadWithFollowUps {
  assigned_to_id?: (number | null);
  business_name: string;
  business_type?: (string | null);
  contact_person: string;
  created_at: string;
  email?: (string | null);
  follow_ups?: Array<FollowUpRead>;
  id: number;
  notes?: (string | null);
  phone?: (string | null);
  status?: LeadStatus;
  updated_at: string;
}
