/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeadStatus } from './lead-status';

/**
 * Each possible value of `LeadStatus`
 */
export const LEAD_STATUS: LeadStatus[] = [
  'new',
  'contacted',
  'demo_scheduled',
  'converted',
  'dropped'
];