/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeadStatus } from '../models/lead-status';
export interface LeadUpdate {
  assigned_to_id?: (number | null);
  business_name?: (string | null);
  business_type?: (string | null);
  contact_person?: (string | null);
  email?: (string | null);
  notes?: (string | null);
  phone?: (string | null);
  status?: (LeadStatus | null);
}
