/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LetterheadAssetRead {
  analysis_status?: string;
  created_at: string;
  extracted_metadata?: {
[key: string]: any;
};
  id: number;
  original_file_url: string;
  tenant_id: number;
}
