/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationRead {
  address?: (string | null);
  created_at: string;
  default_form_id?: (number | null);
  id: number;
  name: string;
  slug: string;
  tenant_id: number;
}
