/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationUpdate {
  address?: (string | null);
  default_form_id?: (number | null);
  name?: (string | null);
  slug?: (string | null);
}
