/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationCreate {
  address?: (string | null);
  default_form_id?: (number | null);
  name: string;
  slug: string;
  tenant_id?: (number | null);
}
