/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnboardingStatus } from './onboarding-status';

/**
 * Each possible value of `OnboardingStatus`
 */
export const ONBOARDING_STATUS: OnboardingStatus[] = [
  'pending',
  'in_progress',
  'completed'
];