/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnboardingStatus } from '../models/onboarding-status';
export interface OnboardingUpdate {
  branding_configured?: (boolean | null);
  form_created?: (boolean | null);
  notes?: (string | null);
  owner_invited?: (boolean | null);
  qr_generated?: (boolean | null);
  status?: (OnboardingStatus | null);
}
