/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnboardingStatus } from '../models/onboarding-status';
export interface OnboardingWithTenant {
  branding_configured?: boolean;
  created_at: string;
  form_created?: boolean;
  id: number;
  notes?: (string | null);
  owner_invited?: boolean;
  qr_generated?: boolean;
  status?: OnboardingStatus;
  tenant_id: number;
  tenant_name: string;
  tenant_slug: string;
  updated_at: string;
}
