/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MonthlyStat } from '../models/monthly-stat';
export interface PerformanceMetrics {
  avg_onboarding_days: number;
  conversion_rate: number;
  leads_converted: number;
  leads_total: number;
  monthly_stats: Array<MonthlyStat>;
  target_conversions?: number;
  target_leads?: number;
  tenants_activated: number;
}
