/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantBranding } from '../models/tenant-branding';
export interface PublicFormRead {
  form_schema?: {
[key: string]: any;
};
  id: number;
  is_default?: boolean;
  is_published?: boolean;
  slug: string;
  tenant: TenantBranding;
  title: string;
}
