/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubscriptionPlanRead {
  billing_cycle?: string;
  description?: (string | null);
  id: number;
  is_active?: boolean;
  is_default?: boolean;
  max_forms: number;
  max_locations?: number;
  max_responses_per_month: number;
  max_team_members?: number;
  name: string;
  price_monthly: number;
}
