/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SystemLog } from '../models/system-log';
export interface SystemHealth {
  active_workers: number;
  api_uptime_seconds: number;
  db_connected: boolean;
  error_rate_24h: number;
  recent_logs: Array<SystemLog>;
  status: string;
}
