/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SystemSetting {
  description?: (string | null);
  key: string;
  updated_at?: string;
  value?: {
[key: string]: any;
};
}
