/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPriority } from '../models/task-priority';
import { TaskStatus } from '../models/task-status';
export interface TaskWithContext {
  assigned_to_id: number;
  created_at: string;
  due_date: string;
  id: number;
  lead_id?: (number | null);
  lead_name?: (string | null);
  notes?: (string | null);
  priority?: TaskPriority;
  status?: TaskStatus;
  tenant_id?: (number | null);
  tenant_name?: (string | null);
  title: string;
  updated_at: string;
}
