/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPriority } from '../models/task-priority';
import { TaskStatus } from '../models/task-status';
export interface TaskCreate {
  assigned_to_id: number;
  due_date: string;
  lead_id?: (number | null);
  notes?: (string | null);
  priority?: TaskPriority;
  status?: TaskStatus;
  tenant_id?: (number | null);
  title: string;
}
