/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPriority } from '../models/task-priority';
import { TaskStatus } from '../models/task-status';
export interface TaskUpdate {
  due_date?: (string | null);
  lead_id?: (number | null);
  notes?: (string | null);
  priority?: (TaskPriority | null);
  status?: (TaskStatus | null);
  tenant_id?: (number | null);
  title?: (string | null);
}
