/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantUsage } from '../models/tenant-usage';
export interface TenantWithAdmin {
  accent_color?: (string | null);
  address?: (string | null);
  admin_email?: (string | null);
  assigned_fleeter_id?: (number | null);
  billing_address?: (string | null);
  created_at: string;
  font_family?: (string | null);
  id: number;
  is_active?: boolean;
  is_branding_approved?: boolean;
  logo_position?: string;
  logo_url?: (string | null);
  name: string;
  plan_id?: (number | null);
  primary_color?: (string | null);
  secondary_color?: (string | null);
  slug: string;
  tagline?: (string | null);
  usage?: (TenantUsage | null);
}
