/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantUsage {
  forms_count: number;
  locations_count: number;
  max_forms?: number;
  max_submissions?: number;
  submissions_count: number;
}
