/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsageSnapshot } from '../models/usage-snapshot';
export interface TenantSalesView {
  admin_email?: (string | null);
  created_at: string;
  flags: Array<string>;
  id: number;
  is_active: boolean;
  name: string;
  onboarding_id: (number | null);
  plan_name: (string | null);
  slug: string;
  usage: UsageSnapshot;
}
