/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantCreateRequest {
  accent_color?: (string | null);
  address?: (string | null);
  admin_designation?: (string | null);
  admin_email: string;
  admin_full_name: string;
  admin_mobile?: (string | null);
  admin_password?: (string | null);
  assigned_fleeter_id?: (number | null);
  billing_address?: (string | null);
  font_family?: (string | null);
  is_active?: boolean;
  is_branding_approved?: boolean;
  logo_position?: string;
  logo_url?: (string | null);
  name: string;
  plan_id?: (number | null);
  primary_color?: (string | null);
  secondary_color?: (string | null);
  should_auto_generate_password?: boolean;
  slug: string;
  tagline?: (string | null);
}
