/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantBranding {
  accent_color?: (string | null);
  address?: (string | null);
  font_family?: (string | null);
  is_branding_approved?: boolean;
  logo_position?: string;
  logo_url?: (string | null);
  name: string;
  primary_color?: (string | null);
  secondary_color?: (string | null);
  tagline?: (string | null);
}
