/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DailyMetric } from '../models/daily-metric';
import { TenantMetric } from '../models/tenant-metric';
export interface UsageMetrics {
  daily_submissions: Array<DailyMetric>;
  rate_limit_triggers: number;
  requests_per_minute: number;
  top_tenants: Array<TenantMetric>;
}
