/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface UserCreate {
  designation?: (string | null);
  email: string;
  email_notifications?: boolean;
  full_name?: (string | null);
  is_active?: boolean;
  mobile_number?: (string | null);
  password: string;
  push_notifications?: boolean;
  role?: UserRole;
  tenant_id?: (number | null);
}
