/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdate {
  designation?: (string | null);
  email?: (string | null);
  email_notifications?: (boolean | null);
  full_name?: (string | null);
  mobile_number?: (string | null);
  push_notifications?: (boolean | null);
}
