/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from './user-role';

/**
 * Each possible value of `UserRole`
 */
export const USER_ROLE: UserRole[] = [
  'super_admin',
  'fleeter',
  'tenant_admin',
  'tenant_staff'
];