/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface UserRead {
  created_at: string;
  designation?: (string | null);
  email: string;
  email_notifications?: boolean;
  full_name?: (string | null);
  id: number;
  is_active?: boolean;
  last_login: (string | null);
  mobile_number?: (string | null);
  push_notifications?: boolean;
  role?: UserRole;
  tenant_id?: (number | null);
}
